# version: '3.8'

services:
  nextjs:
    image: ghcr.io/zalongwa-technologies/saris-react-frontend:new
    container_name: saris-nextjs
    restart: unless-stopped
    ports:
      - "${NEXT_PUBLIC_PORT:-3500}:3500"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.saris-nextjs.rule=Host(`sarisdemo.saris.info.tz`)
      - traefik.http.routers.saris-nextjs.entrypoints=websecure
      - traefik.http.routers.saris-nextjs.tls.certresolver=production
      - traefik.http.services.saris-nextjs.loadbalancer.server.port=3500
    networks:
      - traefik

networks:
  traefik:
    external: true
